"""Add users table

Revision ID: 1595f4d4b09a
Revises: 
Create Date: 2020-10-07 20:44:04.930922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1595f4d4b09a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_user',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=248), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_user_email'), 'users_user', ['email'], unique=False)
    op.create_index(op.f('ix_users_user_username'), 'users_user', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_username'), table_name='users_user')
    op.drop_index(op.f('ix_users_user_email'), table_name='users_user')
    op.drop_table('users_user')
    # ### end Alembic commands ###
